### ISSUE TITLE
Error creating container for current job (permission issue ?)

### ISSUE THREAD

**Issue by ASGdev** [ASGdev/crocoite-runner-stack#1]
(node:7) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, mkdir '/root/crocoite/s9.www.tvn.hu_1561721098362'
    at Object.mkdirSync (fs.js:757:3)
    at resolve (/crocoite-runner-stack/runner.js:27:6)
    at new Promise (<anonymous>)
    at runTask (/crocoite-runner-stack/runner.js:19:9)
    at runJob (/crocoite-runner-stack/runner.js:98:10)
    at /crocoite-runner-stack/runner.js:152:2
    at Layer.handle [as handle_request] (/crocoite-runner-stack/node_modules/express/lib/router/layer.js:95:5)
    at next (/crocoite-runner-stack/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/crocoite-runner-stack/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/crocoite-runner-stack/node_modules/express/lib/router/layer.js:95:5)
(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:7) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ASGdev** [comment]
Container is hardcoded
